TemplateApp/urls.py
from django.urls import path
from . import views

app_name = "TemplateApp"
urlpatterns = [
    path("", views.index, name="index"),
    path("home/<first_name>/<last_name>", views.home, name="home"),
    path("sample1/", views.sample1, name="sample1"),
    path("sample2/", views.sample2, name="sample2"),
    path("sample/", views.sample, name="sample"),
    path("sample3/", views.sample3, name="sample3"),
]

TemplateProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("template_app/", include("TemplateApp.urls")),
]

TemplateApp/models.py
from django.db import models

# Create your models here.

TemplateApp/views.py
from itertools import count
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {
        "value": "Hello",
        "name": "Onishi"
    }
    return render(request, "TemplateApp/index.html", context)


def home(request, first_name, last_name):
    my_name = f"{first_name} {last_name}"
    favorite_fruits = ["Apple", "Grape", "Lemon"]
    my_info = {
        "name": "Taro",
        "age": 18
    }
    status = 20

    return render(request, "TemplateApp/home.html", context={
        "my_name": my_name, 
        "favorite_fluits": favorite_fruits,
        "my_info": my_info,
        "status": status
    })


def sample1(request):
    return render(request, "TemplateApp/sample1.html")


def sample2(request):
    return render(request, "TemplateApp/sample2.html")


def sample(request):
    name = "Onishi Ryosuke"
    height = 169.5
    weight = 56.4
    bmi = weight / (height / 100)**2
    page_url = "ホームページ: https://www.google.com"
    favorite_fruits = [
        "Apple", "Grape", "Lemon"
    ]
    msg = """hello
    my name is
    onishi
    """
    msg2 = "1234567890"
    return render(request, "TemplateApp/sample.html", context={
        "name": name,
        "bmi": bmi,
        "page_url": page_url,
        "fruits": favorite_fruits,
        "msg": msg,
        "msg2": msg2
    })


class Country:
    def __init__(self, name, population, capital):
        self.name = name
        self.population = population
        self.capital = capital


def sample3(request):
    country = Country("Japan", 100000000, "Tokyo")
    return render(request, "TemplateApp/sample3.html", context={
        "country": country
    })

templates/TemplateApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Page{% endblock title %}</title>
</head>
<body>
    <h1>My Page</h1>
    {% block content %}{% endblock content %}
</body>
</html>

templates/TemplateApp/home.html
{% load event_tags %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {# <h1>Name: {{ my_name }}</h1> #}
    {# <h2>果物: {{ favorite_fluits.2 }}</h2> #}
    {# <h3>年齢: {{ my_info.age }}</h3> #}
    <h1>{{ my_name }}</h1>
    <ul>
        {% for fruit in favorite_fluits %}
            <li>{{ fruit }}</li>
        {% endfor %}
    </ul>

    {% if "grape" in favorite_fluits %}
        <p>Grageはあります。</p>
    {% elif "lemon" in favorite_fluits %}
        <p>Lemonはあります。</p>
    {% else %}
        <p>Not Found.</p>
    {% endif %}

    {% if "age" in my_info %}
        {% if my_info.age < 20 %}
            <p>未成年です。</p>
        {% else %}
            <p>成人しています。</p>
        {% endif %}
    {% endif %}

    {% if my_info.name != "Taro" %}
        <p>Taroではありません。</p>
    {% endif %}

    <p>{{ status|status_to_string:"AAA" }}</p>
</body>
</html>

templates/TemplateApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{value}} {{name}} !!</h1>
</body>
</html>

templates/TemplateApp/sample.html
{% load static %}
<link rel="stylesheet" type="text/css", href="{% static 'home.css' %}">

<h1>{{ name|upper }}</h1>
<h1>{{ page_url|urlize }}</h1>
<p>BMI: {{ bmi|floatformat:2 }}</p>
<p>給料: {{ salary|default:"秘密" }}</p>
<p>{{ fruits|random|lower }}</p>
<p>{{ fruits|join:", " }}</p>
<p>{{ msg|linebreaks }}</p>
<p>{{ msg2|truncatechars:7 }}</p>

{% filter upper %}
<p>aaa</p>
<h1>bbb</h1>
{% endfilter %}

<a href="{% url 'TemplateApp:home' first_name='Saburou' last_name='Konishi'%}">Home</a>

<img src="{% static 'cat.jpg' %}" alt="cat image">

templates/TemplateApp/sample1.html
{% extends 'TemplateApp/base.html' %}

{% block title %}Sample1 {{ block.super }}{% endblock title %}
{% block content %}
<p>This is sample1 page.</p>
{% endblock content %}

templates/TemplateApp/sample2.html
{% extends 'TemplateApp/base.html' %}

{% block title %}Sample2 {{ block.super }}{% endblock title %}
{% block content %}
<p>This is sample2 page.</p>
{% endblock content %}

templates/TemplateApp/sample3.html
国名: {{ country.name }}
人口: {{ country.population }}
首都: {{ country.capital }}